// Package config loads and validates the repo-local .keyfold.yml (or the
// pre-rename .repo-enc.yml), merged
// with an optional global override file for machine-local defaults (e.g.
// which key backend to use).
package config

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"regexp"

	"github.com/OpScaleHub/keyfold/internal/gpgutil"
	"gopkg.in/yaml.v3"
)

// FileName is the repo-local config file a new repository gets, committed
// to the repo.
const FileName = ".keyfold.yml"

// LegacyFileName is the config file name used before the Keyfold rename. A
// repository that has it keeps using it -- with the .repo-enc/ key paths it
// implies -- unchanged; nothing needs migrating. Having both is an error.
const LegacyFileName = ".repo-enc.yml"

// Path returns the config file repoRoot uses: LegacyFileName if only that
// one exists, otherwise FileName (whether or not it exists yet).
func Path(repoRoot string) (string, error) {
	cur := filepath.Join(repoRoot, FileName)
	legacy := filepath.Join(repoRoot, LegacyFileName)
	curOK, err := exists(cur)
	if err != nil {
		return "", err
	}
	legacyOK, err := exists(legacy)
	if err != nil {
		return "", err
	}
	switch {
	case curOK && legacyOK:
		return "", fmt.Errorf("config: both %s and %s exist -- keep one (they are the same format; `git mv %s %s` renames the old one)", FileName, LegacyFileName, LegacyFileName, FileName)
	case legacyOK:
		return legacy, nil
	default:
		return cur, nil
	}
}

func exists(path string) (bool, error) {
	_, err := os.Stat(path)
	if err == nil {
		return true, nil
	}
	if os.IsNotExist(err) {
		return false, nil
	}
	return false, err
}

// IsLegacyFile reports whether path names the pre-rename config file.
func IsLegacyFile(path string) bool { return filepath.Base(path) == LegacyFileName }

// CurrentVersion is the only config schema version this build understands.
const CurrentVersion = 1

// Config is the merged, validated configuration for a repository.
type Config struct {
	Version    int      `yaml:"version"`
	Patterns   []string `yaml:"patterns"`
	Exclude    []string `yaml:"exclude,omitempty"`
	KeyBackend string   `yaml:"key_backend"`
	KeySource  string   `yaml:"key_source"`
	// RepoID is a random per-repository identifier, generated by `init`
	// and committed. Whole-file encryption folds it into the AEAD's
	// additional-authenticated-data (a v2 envelope), so a ciphertext blob
	// sealed here fails authentication if dropped into another repository
	// at the same path -- even one that happens to share the key. Empty on
	// repos initialised before this existed: those keep sealing v1
	// (path-only AAD) and stay fully readable. Never change it by hand --
	// existing v2 blobs would stop verifying.
	RepoID string `yaml:"repo_id,omitempty"`
	// GPGRecipients are GPG fingerprints the key is wrapped to when
	// KeyBackend is "gpg". Not secret — these are public key
	// identifiers — so this is committed as part of the repo config,
	// same as Patterns/Exclude.
	GPGRecipients []string `yaml:"gpg_recipients,omitempty"`
	// K8sSecretPaths are repo-relative paths (not globs — an explicit
	// list, since expected usage is a handful of manifests) opted into
	// kubectl-keyfold's per-value encryption instead of Keyfold's
	// whole-file encryption. Independent of Patterns: a repo can use
	// either, both, or neither.
	K8sSecretPaths []string `yaml:"k8s_secret_paths,omitempty"`
	// K8sPlaintextKeys allowlists specific stringData keys, per
	// K8sSecretPaths path, that are intentionally left unencrypted (e.g.
	// a non-secret placeholder living alongside real credentials in the
	// same manifest). verify/hooks treat any stringData value that is
	// neither repo-enc:v1: ciphertext nor listed here as an accidental
	// plaintext leak.
	K8sPlaintextKeys map[string][]string `yaml:"k8s_plaintext_keys,omitempty"`
}

// validBackends are the key_backend values recognized by this build.
// "kms" is reserved for a future backend behind the same
// keybackend.Backend interface; selecting it today is a validation
// error rather than a silent no-op.
var validBackends = map[string]bool{
	"file": true,
	"env":  true,
	"gpg":  true,
}

// DefaultKeySourceFor returns the default key_source for a given
// key_backend. "gpg" gets a distinct default from "file" (".keyfold/key.gpg"
// vs ".keyfold/key") since the two are semantically different — one
// gitignored/secret, one meant to be committed — and switching backends
// shouldn't silently collide with a stale key from the other.
func DefaultKeySourceFor(backend string) string {
	return keySourceFor(".keyfold", backend)
}

// legacyKeySourceFor is DefaultKeySourceFor for a repo still on
// LegacyFileName, whose keys live under .repo-enc/.
func legacyKeySourceFor(backend string) string {
	return keySourceFor(".repo-enc", backend)
}

func keySourceFor(dir, backend string) string {
	if backend == "gpg" {
		return dir + "/key.gpg"
	}
	return dir + "/key"
}

func defaults(legacy bool) *Config {
	ks := DefaultKeySourceFor("file")
	if legacy {
		ks = legacyKeySourceFor("file")
	}
	return &Config{
		Version:    CurrentVersion,
		KeyBackend: "file",
		KeySource:  ks,
	}
}

// NewRepoID returns a fresh random repo id: 16 bytes, hex-encoded. Not a
// secret -- it is committed in the repo config -- just an identifier.
func NewRepoID() (string, error) {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("config: read random for repo_id: %w", err)
	}
	return hex.EncodeToString(b), nil
}

// validRepoID matches the output of NewRepoID plus a little slack for
// hand-written ids.
var validRepoID = regexp.MustCompile(`^[A-Za-z0-9_.-]{8,64}$`)

// GlobalConfigDirEnvVar overrides where GlobalPath looks, bypassing OS
// convention detection entirely. Useful for reproducible CI/container
// setups and for tests, which otherwise can't isolate the global config
// path portably (os.UserConfigDir ignores XDG_CONFIG_HOME on macOS by
// design, unlike on Linux).
const GlobalConfigDirEnvVar = "KEYFOLD_CONFIG_DIR"

// LegacyGlobalConfigDirEnvVar is the pre-rename name of
// GlobalConfigDirEnvVar, still honoured when the new one is unset.
const LegacyGlobalConfigDirEnvVar = "REPO_ENC_CONFIG_DIR"

// GlobalPath returns the path to the user's global override config,
// respecting OS conventions (XDG on Linux, Application Support on macOS,
// AppData on Windows) via os.UserConfigDir, unless GlobalConfigDirEnvVar
// (or its legacy name) is set. Under the OS config dir it is
// keyfold/config.yml, falling back to the pre-rename repo-enc/config.yml
// when only that one exists.
func GlobalPath() (string, error) {
	for _, v := range []string{GlobalConfigDirEnvVar, LegacyGlobalConfigDirEnvVar} {
		if dir := os.Getenv(v); dir != "" {
			return filepath.Join(dir, "config.yml"), nil
		}
	}
	dir, err := os.UserConfigDir()
	if err != nil {
		return "", fmt.Errorf("config: resolve user config dir: %w", err)
	}
	cur := filepath.Join(dir, "keyfold", "config.yml")
	legacy := filepath.Join(dir, "repo-enc", "config.yml")
	if ok, _ := exists(cur); !ok {
		if ok, _ := exists(legacy); ok {
			return legacy, nil
		}
	}
	return cur, nil
}

// Load reads the repo-local config (see Path), merges in the global
// override file if present, and validates the result.
func Load(repoRoot string) (*Config, error) {
	repoPath, err := Path(repoRoot)
	if err != nil {
		return nil, err
	}
	data, err := os.ReadFile(repoPath)
	if err != nil {
		return nil, fmt.Errorf("config: read %s: %w", repoPath, err)
	}
	repo, err := ParseBytes(data)
	if err != nil {
		return nil, fmt.Errorf("config: read %s: %w", repoPath, err)
	}
	return MergeGlobalFor(repoPath, repo)
}

// ParseBytes parses raw YAML into a Config, without merging global
// config or validating. Exposed so callers that source repo config from
// somewhere other than the checked-out working tree — e.g. revision-
// pinned verification, which reads the config as committed at a
// specific git revision rather than off disk — can still go through the
// same merge/validate path MergeGlobal provides.
func ParseBytes(data []byte) (*Config, error) {
	var c Config
	if err := yaml.Unmarshal(data, &c); err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}
	return &c, nil
}

// MergeGlobal layers the machine-local global override config (if
// present) under repo, following the precedence rules below, and
// validates the result.
//
// Merge semantics: scalar fields (key_backend, key_source) are repo-local
// if set there, else global, else built-in default. Patterns,
// gpg_recipients, and k8s_secret_paths are the union of global and
// repo-local entries, so a user's personal defaults (e.g. "*.secret.*"
// patterns, or always including their own key as a gpg recipient) apply
// everywhere without needing to be copy-pasted into every repo — since
// these fields only ever *expand* what's protected or who can decrypt,
// a global addition can't weaken repo policy.
//
// exclude and k8s_plaintext_keys are different: both can only *shrink*
// the effectively-protected set, so unioning a global entry into them
// would let a machine-local config silently carve a hole out of a
// repository's committed protection. These two fields are therefore
// taken from repo alone, never merged with a global value.
func MergeGlobal(repo *Config) (*Config, error) {
	return MergeGlobalFor(FileName, repo)
}

// MergeGlobalFor is MergeGlobal for a repo config read from file name (only
// its base name matters): a LegacyFileName config defaults key_source to
// the pre-rename .repo-enc/ paths, so a repo that never set it explicitly
// keeps finding its key.
func MergeGlobalFor(name string, repo *Config) (*Config, error) {
	cfg := defaults(IsLegacyFile(name))

	if globalPath, err := GlobalPath(); err == nil {
		if global, err := loadFile(globalPath); err == nil {
			mergeInto(cfg, global)
		} else if !os.IsNotExist(err) {
			return nil, fmt.Errorf("config: read global config: %w", err)
		}
	}
	mergeInto(cfg, repo)
	cfg.Exclude = append([]string{}, repo.Exclude...)
	cfg.K8sPlaintextKeys = repo.K8sPlaintextKeys

	if err := cfg.Validate(); err != nil {
		return nil, err
	}
	return cfg, nil
}

func loadFile(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	return ParseBytes(data)
}

// mergeInto layers overlay onto base in place for the fields where a
// global contribution is safe (see MergeGlobal's doc) — Exclude and
// K8sPlaintextKeys are handled separately by the caller.
func mergeInto(base, overlay *Config) {
	if overlay.Version != 0 {
		base.Version = overlay.Version
	}
	if overlay.KeyBackend != "" {
		base.KeyBackend = overlay.KeyBackend
	}
	if overlay.KeySource != "" {
		base.KeySource = overlay.KeySource
	}
	if overlay.RepoID != "" {
		// repo-local only; a global override never contributes a repo id.
		base.RepoID = overlay.RepoID
	}
	base.Patterns = unionDedup(base.Patterns, overlay.Patterns)
	base.GPGRecipients = unionDedup(base.GPGRecipients, overlay.GPGRecipients)
	base.K8sSecretPaths = unionDedup(base.K8sSecretPaths, overlay.K8sSecretPaths)
}

func unionDedup(a, b []string) []string {
	seen := make(map[string]bool, len(a)+len(b))
	out := make([]string, 0, len(a)+len(b))
	for _, s := range append(append([]string{}, a...), b...) {
		if s == "" || seen[s] {
			continue
		}
		seen[s] = true
		out = append(out, s)
	}
	return out
}

// Validate checks that the config is well-formed and usable.
func (c *Config) Validate() error {
	if c.Version != CurrentVersion {
		return fmt.Errorf("config: unsupported version %d (expected %d)", c.Version, CurrentVersion)
	}
	if len(c.Patterns) == 0 && len(c.K8sSecretPaths) == 0 {
		return fmt.Errorf("config: at least one entry in 'patterns' or 'k8s_secret_paths' is required")
	}
	if !validBackends[c.KeyBackend] {
		return fmt.Errorf("config: unknown key_backend %q", c.KeyBackend)
	}
	if c.KeySource == "" {
		return fmt.Errorf("config: key_source must not be empty")
	}
	if c.RepoID != "" && !validRepoID.MatchString(c.RepoID) {
		return fmt.Errorf("config: repo_id %q is not 8-64 chars of [A-Za-z0-9_.-] -- regenerate with `git keyfold init` in a fresh repo, or remove it to fall back to v1 envelopes", c.RepoID)
	}
	if c.KeyBackend == "gpg" && len(c.GPGRecipients) == 0 {
		return fmt.Errorf("config: key_backend \"gpg\" requires at least one entry in gpg_recipients")
	}
	for _, r := range c.GPGRecipients {
		if !gpgutil.ValidFingerprint(r) {
			return fmt.Errorf("config: gpg_recipients entry %q is not a full GPG fingerprint (40 or 64 hex characters) — short IDs and emails are ambiguous and not accepted", r)
		}
	}
	for _, p := range append(append([]string{}, c.Patterns...), c.Exclude...) {
		if _, err := filepath.Match(lastSegment(p), "x"); err != nil {
			return fmt.Errorf("config: invalid glob pattern %q: %w", p, err)
		}
	}
	return nil
}

const configHeader = "# Keyfold config: https://github.com/OpScaleHub/keyfold\n" +
	"# 'patterns' are glob paths (relative to repo root, '**' matches any depth)\n" +
	"# that get transparently encrypted by the installed git hooks.\n"

// WriteDefault writes a starter config to repoRoot/.keyfold.yml. It
// refuses to overwrite an existing config (either name) so `init` stays
// idempotent.
func WriteDefault(repoRoot string, patterns []string) (string, error) {
	cfg := defaults(false)
	cfg.Patterns = patterns
	id, err := NewRepoID()
	if err != nil {
		return "", err
	}
	cfg.RepoID = id
	return WriteConfig(repoRoot, cfg)
}

// WriteConfig writes cfg as the starter .keyfold.yml, refusing to
// overwrite an existing config of either name (same idempotency contract
// as WriteDefault) -- it returns the existing file's path instead.
// Used by `init` when the caller has chosen a non-default key backend
// (e.g. gpg) and needs to set key_backend/key_source/gpg_recipients
// before the file is ever written.
func WriteConfig(repoRoot string, cfg *Config) (string, error) {
	path, err := Path(repoRoot)
	if err != nil {
		return "", err
	}
	if ok, err := exists(path); err != nil {
		return "", err
	} else if ok {
		return path, nil
	}
	return path, writeConfigFile(path, cfg)
}

// Save overwrites the repo's config file (see Path) with cfg
// unconditionally, unlike
// WriteDefault/WriteConfig's refuse-if-exists guard. Used by adduser/
// removeuser, which are legitimate in-place edits to an already-existing,
// already-customized config rather than a first-time bootstrap.
func Save(repoRoot string, cfg *Config) error {
	path, err := Path(repoRoot)
	if err != nil {
		return err
	}
	return writeConfigFile(path, cfg)
}

func writeConfigFile(path string, cfg *Config) error {
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("config: marshal config: %w", err)
	}
	if err := os.WriteFile(path, []byte(configHeader+string(data)), 0o644); err != nil {
		return fmt.Errorf("config: write %s: %w", path, err)
	}
	return nil
}
